### ISSUE TITLE
Creating a remote should allow arbitrary key-value pairs

### ISSUE THREAD

**Issue by plaflamme** [Johannes11833/rclone_python#10]
Currently, the `create_remote` allows 2 arguments, `client_id` and `client_sercret`, but rclone remotes have very rich configuration properties and these 2 are not sufficient to cover all use-cases.

The simplest approach would probably be to take an arbitrary list of key-value pairs (perhaps as a dict, perharps as a `kwargs`) and pass those verbatim to `rclone remote create <name> <type> [<key>=<value>]*`

For example, to create a gcs backend:

```
create_remote("my-gcs", "gcs", env_auth=True, project_number=123456)
```

**Comment by Johannes11833** [comment]
Yeah that makes sense!

**Comment by Johannes11833** [comment]
By making those changes I also discovered, that client id and secret should be set with key-value options instead of the global flags that I was using so far. Because those two global flags did not affect the config, meaning that those properties were not written to it as they should. 👍
