### ISSUE TITLE
The args command concatenation in master conflicts with the released version

### ISSUE THREAD

**Issue by ligeng8848** [Johannes11833/rclone_python#34]
The args splicing method in the 0.1.12 release is as follows
```
def args2string(args: List[str]) -> str:
out = ""

for item in args:
out += f" {item}"

return out
```
In the latest master version, args splicing uses `join`
If do not pay attention to this, it will cause trouble for old users

**Comment by mmichaelc** [comment]
This is causing a bug. Args added to the command now don't have a leading space.
