### ISSUE TITLE
Detailed Progress

### ISSUE THREAD

**Issue by spooknik** [Johannes11833/rclone_python#7]
Hello, thanks for the nice library. It's working great for me. 

I have a request for more detailed progress bar during a transfer. Rclone's progress shows progress for each file (if there are multiples). I think it would be helpful to also see this  👍  

![image](https://github.com/Johannes11833/rclone_python/assets/40317809/d07608b8-599b-4cfc-9a89-abc0ad494947)

![image](https://github.com/Johannes11833/rclone_python/assets/40317809/ada2b8f2-29dc-4b84-acc6-f4e56e9d6820)

**Comment by Johannes11833** [comment]
Good Idea :+1:
